name: Build

on:
  push:
    branches: [ single_activity ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Unit tests
        run: ./gradlew test
      
      - name: Build
        run: ./gradlew build
        
      - uses: r0adkll/sign-android-release@v1.0.4
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{secrets.SIGNING_KEY}}
          alias: ${{secrets.ALIAS}}
          keyStorePassword: ${{secrets.KEY_STORE_PASSWORD}}
          keyPassword: ${{secrets.KEY_PASSWORD}}
        
      - name: Upload Apk
        uses: actions/upload-artifact@v2.2.2
        with:
          name: app
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Android
          file: ${{steps.sign_app.outputs.signedReleaseFile}}
