name: Build

on:
  push:
    branches: [ single_activity ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Unit tests
        run: ./gradlew test
      
      - name: Build
        run: ./gradlew build
        
      - name: Upload Apk
        uses: actions/upload-artifact@v2.2.2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          groups: Android
          file: app/build/outputs/apk/debug/app-debug.apk
    
    
    
    debug: # optional
