name: Build

on:
  push:
    branches: [ single_activity ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build
        run: ./gradlew build
        
      - name: Upload Apk
        uses: actions/upload-artifact@v2.2.2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
